### ISSUE TITLE
Checkpoint not found

### ISSUE THREAD

**Issue by LecJackS** [yenchenlin1994/DeepLearningFlappyBird#8]
I tried to run this and this showed on the terminal (on ubuntu):

> W tensorflow/core/kernels/io.cc:228] Not found: Unsuccessful TensorSliceReader constructor: Failed to find any matching files for bird-dqn-30000

So I went to the "saved_networks" folder, and "bird-dqn-30000" was there.

Inside the checkpoint file, the content was:

```
model_checkpoint_path: "bird-dqn-30000"
all_model_checkpoint_paths: "bird-dqn-10000"
all_model_checkpoint_paths: "bird-dqn-20000"
all_model_checkpoint_paths: "bird-dqn-30000"
```

I changed the first line to:
```
model_checkpoint_path: "saved_networks/bird-dqn-30000"
all_model_checkpoint_paths: "bird-dqn-10000"
all_model_checkpoint_paths: "bird-dqn-20000"
all_model_checkpoint_paths: "bird-dqn-30000"
```

Worked fine.

I don't know if this is a real issue, or just something messy with my system. Just want to let you know.

**Comment by yenchenlin1994** [comment]
Hello @LecJackS ,
What's your TensorFlow version?

**Comment by LecJackS** [comment]
It was 0.6.0

Upgraded to 0.7.1

Worked perfectly as default.

Sorry about that :shame:

**Comment by yenchenlin1994** [comment]
Don't be haha :smile: 
I will close this issue.

Thanks!

**Comment by petrbel** [comment]
Hi guys,
I have exactly same trouble. My TF version is 0.7.1.
Prepending `saved_networks/` helped as @LecJackS suggested.

Would @yenchenlin1994 consider updating the info?

Regards :)

**Comment by yenchenlin1994** [comment]
Hello @petrbel ,
You mean even if your TF version is 0.7.1 you still need to Prepend `saved_networks/ ` to make it work?

**Comment by petrbel** [comment]
@yenchenlin1994 Exactly. I run Ubuntu 15.04

**Comment by yenchenlin1994** [comment]
hmm ... its's strange.
I can't reproduce the issue.

Hello @LecJackS ,
would you please delete this project on your computer and clone it again, and check if it can run?

**Comment by petrbel** [comment]
I tried it once again. This is the log without any modification:

```
[petr@hellmut ~ ]$ cd /tmp 
[petr@hellmut /tmp ]$ pip show tensorflow
---
Metadata-Version: 2.0
Name: tensorflow
Version: 0.7.1
Summary: TensorFlow helps the tensors flow
Home-page: http://tensorflow.org/
Author: Google Inc.
Author-email: opensource@google.com
Installer: pip
License: Apache 2.0
Location: /usr/local/lib/python3.4/dist-packages
Requires: wheel, numpy, protobuf, six
Classifiers:
  Development Status :: 4 - Beta
  Intended Audience :: Developers
  Intended Audience :: Education
  Intended Audience :: Science/Research
  License :: OSI Approved :: Apache Software License
  Programming Language :: Python :: 2.7
  Topic :: Scientific/Engineering :: Mathematics
  Topic :: Software Development :: Libraries :: Python Modules
  Topic :: Software Development :: Libraries
Entry-points:
  [console_scripts]
  tensorboard = tensorflow.tensorboard.backend.tensorboard:main
[petr@hellmut /tmp ]$ git clone git@github.com:yenchenlin1994/DeepLearningFlappyBird.git
Cloning into 'DeepLearningFlappyBird'...
remote: Counting objects: 196, done.
remote: Compressing objects: 100% (3/3), done.
remote: Total 196 (delta 0), reused 0 (delta 0), pack-reused 192
Receiving objects: 100% (196/196), 66.26 MiB | 1.53 MiB/s, done.
Resolving deltas: 100% (95/95), done.
Checking connectivity... done.
[petr@hellmut /tmp ]$ cd DeepLearningFlappyBird 
[petr@hellmut DeepLearningFlappyBird (master)]$ python deep_q_network.py 
I tensorflow/core/common_runtime/local_device.cc:25] Local device intra op parallelism threads: 4
I tensorflow/core/common_runtime/local_session.cc:45] Local session inter op parallelism threads: 4
W tensorflow/core/kernels/io.cc:212] Not found: Unsuccessful TensorSliceReader constructor: Failed to find any matching files for bird-dqn-2920000
W tensorflow/core/kernels/io.cc:212] Not found: Unsuccessful TensorSliceReader constructor: Failed to find any matching files for bird-dqn-2920000
W tensorflow/core/common_runtime/executor.cc:1027] 0x38f1cb0 Compute status: Not found: Unsuccessful TensorSliceReader constructor: Failed to find any matching files for bird-dqn-2920000
	 [[Node: save/restore_slice = RestoreSlice[dt=DT_FLOAT, preferred_shard=-1, _device="/job:localhost/replica:0/task:0/cpu:0"](_recv_save/Const_0, save/restore_slice/tensor_name, save/restore_slice/shape_and_slice)]]
W tensorflow/core/common_runtime/executor.cc:1027] 0x38f1cb0 Compute status: Not found: Unsuccessful TensorSliceReader constructor: Failed to find any matching files for bird-dqn-2920000
	 [[Node: save/restore_slice_1 = RestoreSlice[dt=DT_FLOAT, preferred_shard=-1, _device="/job:localhost/replica:0/task:0/cpu:0"](_recv_save/Const_0, save/restore_slice_1/tensor_name, save/restore_slice_1/shape_and_slice)]]
W tensorflow/core/kernels/io.cc:212] Not found: Unsuccessful TensorSliceReader constructor: Failed to find any matching files for bird-dqn-2920000
W tensorflow/core/kernels/io.cc:212] Not found: Unsuccessful TensorSliceReader constructor: Failed to find any matching files for bird-dqn-2920000
W tensorflow/core/kernels/io.cc:212] Not found: Unsuccessful TensorSliceReader constructor: Failed to find any matching files for bird-dqn-2920000
W tensorflow/core/common_runtime/executor.cc:1027] 0x38f1cb0 Compute status: Not found: Unsuccessful TensorSliceReader constructor: Failed to find any matching files for bird-dqn-2920000
	 [[Node: save/restore_slice_4 = RestoreSlice[dt=DT_FLOAT, preferred_shard=-1, _device="/job:localhost/replica:0/task:0/cpu:0"](_recv_save/Const_0, save/restore_slice_4/tensor_name, save/restore_slice_4/shape_and_slice)]]
W tensorflow/core/common_runtime/executor.cc:1027] 0x38f1cb0 Compute status: Not found: Unsuccessful TensorSliceReader constructor: Failed to find any matching files for bird-dqn-2920000
	 [[Node: save/restore_slice_2 = RestoreSlice[dt=DT_FLOAT, preferred_shard=-1, _device="/job:localhost/replica:0/task:0/cpu:0"](_recv_save/Const_0, save/restore_slice_2/tensor_name, save/restore_slice_2/shape_and_slice)]]
W tensorflow/core/common_runtime/executor.cc:1027] 0x38f1cb0 Compute status: Not found: Unsuccessful TensorSliceReader constructor: Failed to find any matching files for bird-dqn-2920000
	 [[Node: save/restore_slice_31 = RestoreSlice[dt=DT_FLOAT, preferred_shard=-1, _device="/job:localhost/replica:0/task:0/cpu:0"](_recv_save/Const_0, save/restore_slice_31/tensor_name, save/restore_slice_31/shape_and_slice)]]
W tensorflow/core/kernels/io.cc:212] Not found: Unsuccessful TensorSliceReader constructor: Failed to find any matching files for bird-dqn-2920000
W tensorflow/core/kernels/io.cc:212] Not found: Unsuccessful TensorSliceReader constructor: Failed to find any matching files for bird-dqn-2920000
W tensorflow/core/kernels/io.cc:212] Not found: Unsuccessful TensorSliceReader constructor: Failed to find any matching files for bird-dqn-2920000
W tensorflow/core/common_runtime/executor.cc:1027] 0x38f1cb0 Compute status: Not found: Unsuccessful TensorSliceReader constructor: Failed to find any matching files for bird-dqn-2920000
	 [[Node: save/restore_slice_7 = RestoreSlice[dt=DT_FLOAT, preferred_shard=-1, _device="/job:localhost/replica:0/task:0/cpu:0"](_recv_save/Const_0, save/restore_slice_7/tensor_name, save/restore_slice_7/shape_and_slice)]]
W tensorflow/core/common_runtime/executor.cc:1027] 0x38f1cb0 Compute status: Not found: Unsuccessful TensorSliceReader constructor: Failed to find any matching files for bird-dqn-2920000
	 [[Node: save/restore_slice_6 = RestoreSlice[dt=DT_FLOAT, preferred_shard=-1, _device="/job:localhost/replica:0/task:0/cpu:0"](_recv_save/Const_0, save/restore_slice_6/tensor_name, save/restore_slice_6/shape_and_slice)]]
W tensorflow/core/kernels/io.cc:212] Not found: Unsuccessful TensorSliceReader constructor: Failed to find any matching files for bird-dqn-2920000
W tensorflow/core/common_runtime/executor.cc:1027] 0x38f1cb0 Compute status: Not found: Unsuccessful TensorSliceReader constructor: Failed to find any matching files for bird-dqn-2920000
	 [[Node: save/restore_slice_8 = RestoreSlice[dt=DT_FLOAT, preferred_shard=-1, _device="/job:localhost/replica:0/task:0/cpu:0"](_recv_save/Const_0, save/restore_slice_8/tensor_name, save/restore_slice_8/shape_and_slice)]]
W tensorflow/core/kernels/io.cc:212] Not found: Unsuccessful TensorSliceReader constructor: Failed to find any matching files for bird-dqn-2920000
W tensorflow/core/common_runtime/executor.cc:1027] 0x38f1cb0 Compute status: Not found: Unsuccessful TensorSliceReader constructor: Failed to find any matching files for bird-dqn-2920000
	 [[Node: save/restore_slice_5 = RestoreSlice[dt=DT_FLOAT, preferred_shard=-1, _device="/job:localhost/replica:0/task:0/cpu:0"](_recv_save/Const_0, save/restore_slice_5/tensor_name, save/restore_slice_5/shape_and_slice)]]
W tensorflow/core/common_runtime/executor.cc:1027] 0x38f1cb0 Compute status: Not found: Unsuccessful TensorSliceReader constructor: Failed to find any matching files for bird-dqn-2920000
	 [[Node: save/restore_slice_3 = RestoreSlice[dt=DT_FLOAT, preferred_shard=-1, _device="/job:localhost/replica:0/task:0/cpu:0"](_recv_save/Const_0, save/restore_slice_3/tensor_name, save/restore_slice_3/shape_and_slice)]]
W tensorflow/core/kernels/io.cc:212] Not found: Unsuccessful TensorSliceReader constructor: Failed to find any matching files for bird-dqn-2920000
W tensorflow/core/kernels/io.cc:212] Not found: Unsuccessful TensorSliceReader constructor: Failed to find any matching files for bird-dqn-2920000
W tensorflow/core/kernels/io.cc:212] Not found: Unsuccessful TensorSliceReader constructor: Failed to find any matching files for bird-dqn-2920000
W tensorflow/core/common_runtime/executor.cc:1027] 0x38f1cb0 Compute status: Not found: Unsuccessful TensorSliceReader constructor: Failed to find any matching files for bird-dqn-2920000
	 [[Node: save/restore_slice_12 = RestoreSlice[dt=DT_FLOAT, preferred_shard=-1, _device="/job:localhost/replica:0/task:0/cpu:0"](_recv_save/Const_0, save/restore_slice_12/tensor_name, save/restore_slice_12/shape_and_slice)]]
W tensorflow/core/common_runtime/executor.cc:1027] 0x38f1cb0 Compute status: Not found: Unsuccessful TensorSliceReader constructor: Failed to find any matching files for bird-dqn-2920000
	 [[Node: save/restore_slice_9 = RestoreSlice[dt=DT_FLOAT, preferred_shard=-1, _device="/job:localhost/replica:0/task:0/cpu:0"](_recv_save/Const_0, save/restore_slice_9/tensor_name, save/restore_slice_9/shape_and_slice)]]
W tensorflow/core/kernels/io.cc:212] Not found: Unsuccessful TensorSliceReader constructor: Failed to find any matching files for bird-dqn-2920000
W tensorflow/core/kernels/io.cc:212] Not found: Unsuccessful TensorSliceReader constructor: Failed to find any matching files for bird-dqn-2920000
W tensorflow/core/common_runtime/executor.cc:1027] 0x38f1cb0 Compute status: Not found: Unsuccessful TensorSliceReader constructor: Failed to find any matching files for bird-dqn-2920000
	 [[Node: save/restore_slice_13 = RestoreSlice[dt=DT_FLOAT, preferred_shard=-1, _device="/job:localhost/replica:0/task:0/cpu:0"](_recv_save/Const_0, save/restore_slice_13/tensor_name, save/restore_slice_13/shape_and_slice)]]
W tensorflow/core/kernels/io.cc:212] Not found: Unsuccessful TensorSliceReader constructor: Failed to find any matching files for bird-dqn-2920000
W tensorflow/core/common_runtime/executor.cc:1027] 0x38f1cb0 Compute status: Not found: Unsuccessful TensorSliceReader constructor: Failed to find any matching files for bird-dqn-2920000
	 [[Node: save/restore_slice_14 = RestoreSlice[dt=DT_FLOAT, preferred_shard=-1, _device="/job:localhost/replica:0/task:0/cpu:0"](_recv_save/Const_0, save/restore_slice_14/tensor_name, save/restore_slice_14/shape_and_slice)]]
W tensorflow/core/common_runtime/executor.cc:1027] 0x38f1cb0 Compute status: Not found: Unsuccessful TensorSliceReader constructor: Failed to find any matching files for bird-dqn-2920000
	 [[Node: save/restore_slice_11 = RestoreSlice[dt=DT_FLOAT, preferred_shard=-1, _device="/job:localhost/replica:0/task:0/cpu:0"](_recv_save/Const_0, save/restore_slice_11/tensor_name, save/restore_slice_11/shape_and_slice)]]
W tensorflow/core/common_runtime/executor.cc:1027] 0x38f1cb0 Compute status: Not found: Unsuccessful TensorSliceReader constructor: Failed to find any matching files for bird-dqn-2920000
	 [[Node: save/restore_slice_10 = RestoreSlice[dt=DT_FLOAT, preferred_shard=-1, _device="/job:localhost/replica:0/task:0/cpu:0"](_recv_save/Const_0, save/restore_slice_10/tensor_name, save/restore_slice_10/shape_and_slice)]]
W tensorflow/core/kernels/io.cc:212] Not found: Unsuccessful TensorSliceReader constructor: Failed to find any matching files for bird-dqn-2920000
W tensorflow/core/kernels/io.cc:212] Not found: Unsuccessful TensorSliceReader constructor: Failed to find any matching files for bird-dqn-2920000
W tensorflow/core/kernels/io.cc:212] Not found: Unsuccessful TensorSliceReader constructor: Failed to find any matching files for bird-dqn-2920000
W tensorflow/core/common_runtime/executor.cc:1027] 0x38f1cb0 Compute status: Not found: Unsuccessful TensorSliceReader constructor: Failed to find any matching files for bird-dqn-2920000
	 [[Node: save/restore_slice_16 = RestoreSlice[dt=DT_FLOAT, preferred_shard=-1, _device="/job:localhost/replica:0/task:0/cpu:0"](_recv_save/Const_0, save/restore_slice_16/tensor_name, save/restore_slice_16/shape_and_slice)]]
W tensorflow/core/kernels/io.cc:212] Not found: Unsuccessful TensorSliceReader constructor: Failed to find any matching files for bird-dqn-2920000
W tensorflow/core/common_runtime/executor.cc:1027] 0x38f1cb0 Compute status: Not found: Unsuccessful TensorSliceReader constructor: Failed to find any matching files for bird-dqn-2920000
	 [[Node: save/restore_slice_17 = RestoreSlice[dt=DT_FLOAT, preferred_shard=-1, _device="/job:localhost/replica:0/task:0/cpu:0"](_recv_save/Const_0, save/restore_slice_17/tensor_name, save/restore_slice_17/shape_and_slice)]]
W tensorflow/core/common_runtime/executor.cc:1027] 0x38f1cb0 Compute status: Not found: Unsuccessful TensorSliceReader constructor: Failed to find any matching files for bird-dqn-2920000
	 [[Node: save/restore_slice_15 = RestoreSlice[dt=DT_FLOAT, preferred_shard=-1, _device="/job:localhost/replica:0/task:0/cpu:0"](_recv_save/Const_0, save/restore_slice_15/tensor_name, save/restore_slice_15/shape_and_slice)]]
W tensorflow/core/common_runtime/executor.cc:1027] 0x38f1cb0 Compute status: Not found: Unsuccessful TensorSliceReader constructor: Failed to find any matching files for bird-dqn-2920000
	 [[Node: save/restore_slice_18 = RestoreSlice[dt=DT_FLOAT, preferred_shard=-1, _device="/job:localhost/replica:0/task:0/cpu:0"](_recv_save/Const_0, save/restore_slice_18/tensor_name, save/restore_slice_18/shape_and_slice)]]
W tensorflow/core/kernels/io.cc:212] Not found: Unsuccessful TensorSliceReader constructor: Failed to find any matching files for bird-dqn-2920000
W tensorflow/core/common_runtime/executor.cc:1027] 0x38f1cb0 Compute status: Not found: Unsuccessful TensorSliceReader constructor: Failed to find any matching files for bird-dqn-2920000
	 [[Node: save/restore_slice_20 = RestoreSlice[dt=DT_FLOAT, preferred_shard=-1, _device="/job:localhost/replica:0/task:0/cpu:0"](_recv_save/Const_0, save/restore_slice_20/tensor_name, save/restore_slice_20/shape_and_slice)]]
W tensorflow/core/kernels/io.cc:212] Not found: Unsuccessful TensorSliceReader constructor: Failed to find any matching files for bird-dqn-2920000
W tensorflow/core/kernels/io.cc:212] Not found: Unsuccessful TensorSliceReader constructor: Failed to find any matching files for bird-dqn-2920000
W tensorflow/core/common_runtime/executor.cc:1027] 0x38f1cb0 Compute status: Not found: Unsuccessful TensorSliceReader constructor: Failed to find any matching files for bird-dqn-2920000
	 [[Node: save/restore_slice_21 = RestoreSlice[dt=DT_FLOAT, preferred_shard=-1, _device="/job:localhost/replica:0/task:0/cpu:0"](_recv_save/Const_0, save/restore_slice_21/tensor_name, save/restore_slice_21/shape_and_slice)]]
W tensorflow/core/common_runtime/executor.cc:1027] 0x38f1cb0 Compute status: Not found: Unsuccessful TensorSliceReader constructor: Failed to find any matching files for bird-dqn-2920000
	 [[Node: save/restore_slice_22 = RestoreSlice[dt=DT_FLOAT, preferred_shard=-1, _device="/job:localhost/replica:0/task:0/cpu:0"](_recv_save/Const_0, save/restore_slice_22/tensor_name, save/restore_slice_22/shape_and_slice)]]
W tensorflow/core/kernels/io.cc:212] Not found: Unsuccessful TensorSliceReader constructor: Failed to find any matching files for bird-dqn-2920000
W tensorflow/core/kernels/io.cc:212] Not found: Unsuccessful TensorSliceReader constructor: Failed to find any matching files for bird-dqn-2920000
W tensorflow/core/common_runtime/executor.cc:1027] 0x38f1cb0 Compute status: Not found: Unsuccessful TensorSliceReader constructor: Failed to find any matching files for bird-dqn-2920000
	 [[Node: save/restore_slice_19 = RestoreSlice[dt=DT_FLOAT, preferred_shard=-1, _device="/job:localhost/replica:0/task:0/cpu:0"](_recv_save/Const_0, save/restore_slice_19/tensor_name, save/restore_slice_19/shape_and_slice)]]
W tensorflow/core/kernels/io.cc:212] Not found: Unsuccessful TensorSliceReader constructor: Failed to find any matching files for bird-dqn-2920000
W tensorflow/core/kernels/io.cc:212] Not found: Unsuccessful TensorSliceReader constructor: Failed to find any matching files for bird-dqn-2920000
W tensorflow/core/common_runtime/executor.cc:1027] 0x38f1cb0 Compute status: Not found: Unsuccessful TensorSliceReader constructor: Failed to find any matching files for bird-dqn-2920000
	 [[Node: save/restore_slice_23 = RestoreSlice[dt=DT_FLOAT, preferred_shard=-1, _device="/job:localhost/replica:0/task:0/cpu:0"](_recv_save/Const_0, save/restore_slice_23/tensor_name, save/restore_slice_23/shape_and_slice)]]
W tensorflow/core/kernels/io.cc:212] Not found: Unsuccessful TensorSliceReader constructor: Failed to find any matching files for bird-dqn-2920000
W tensorflow/core/common_runtime/executor.cc:1027] 0x38f1cb0 Compute status: Not found: Unsuccessful TensorSliceReader constructor: Failed to find any matching files for bird-dqn-2920000
	 [[Node: save/restore_slice_25 = RestoreSlice[dt=DT_FLOAT, preferred_shard=-1, _device="/job:localhost/replica:0/task:0/cpu:0"](_recv_save/Const_0, save/restore_slice_25/tensor_name, save/restore_slice_25/shape_and_slice)]]
W tensorflow/core/common_runtime/executor.cc:1027] 0x38f1cb0 Compute status: Not found: Unsuccessful TensorSliceReader constructor: Failed to find any matching files for bird-dqn-2920000
	 [[Node: save/restore_slice_24 = RestoreSlice[dt=DT_FLOAT, preferred_shard=-1, _device="/job:localhost/replica:0/task:0/cpu:0"](_recv_save/Const_0, save/restore_slice_24/tensor_name, save/restore_slice_24/shape_and_slice)]]
W tensorflow/core/common_runtime/executor.cc:1027] 0x38f1cb0 Compute status: Not found: Unsuccessful TensorSliceReader constructor: Failed to find any matching files for bird-dqn-2920000
	 [[Node: save/restore_slice_26 = RestoreSlice[dt=DT_FLOAT, preferred_shard=-1, _device="/job:localhost/replica:0/task:0/cpu:0"](_recv_save/Const_0, save/restore_slice_26/tensor_name, save/restore_slice_26/shape_and_slice)]]
W tensorflow/core/kernels/io.cc:212] Not found: Unsuccessful TensorSliceReader constructor: Failed to find any matching files for bird-dqn-2920000
W tensorflow/core/kernels/io.cc:212] Not found: Unsuccessful TensorSliceReader constructor: Failed to find any matching files for bird-dqn-2920000
W tensorflow/core/common_runtime/executor.cc:1027] 0x38f1cb0 Compute status: Not found: Unsuccessful TensorSliceReader constructor: Failed to find any matching files for bird-dqn-2920000
	 [[Node: save/restore_slice_27 = RestoreSlice[dt=DT_FLOAT, preferred_shard=-1, _device="/job:localhost/replica:0/task:0/cpu:0"](_recv_save/Const_0, save/restore_slice_27/tensor_name, save/restore_slice_27/shape_and_slice)]]
W tensorflow/core/kernels/io.cc:212] Not found: Unsuccessful TensorSliceReader constructor: Failed to find any matching files for bird-dqn-2920000
W tensorflow/core/kernels/io.cc:212] Not found: Unsuccessful TensorSliceReader constructor: Failed to find any matching files for bird-dqn-2920000
W tensorflow/core/common_runtime/executor.cc:1027] 0x38f1cb0 Compute status: Not found: Unsuccessful TensorSliceReader constructor: Failed to find any matching files for bird-dqn-2920000
	 [[Node: save/restore_slice_30 = RestoreSlice[dt=DT_FLOAT, preferred_shard=-1, _device="/job:localhost/replica:0/task:0/cpu:0"](_recv_save/Const_0, save/restore_slice_30/tensor_name, save/restore_slice_30/shape_and_slice)]]
W tensorflow/core/common_runtime/executor.cc:1027] 0x38f1cb0 Compute status: Not found: Unsuccessful TensorSliceReader constructor: Failed to find any matching files for bird-dqn-2920000
	 [[Node: save/restore_slice_28 = RestoreSlice[dt=DT_FLOAT, preferred_shard=-1, _device="/job:localhost/replica:0/task:0/cpu:0"](_recv_save/Const_0, save/restore_slice_28/tensor_name, save/restore_slice_28/shape_and_slice)]]
W tensorflow/core/common_runtime/executor.cc:1027] 0x38f1cb0 Compute status: Not found: Unsuccessful TensorSliceReader constructor: Failed to find any matching files for bird-dqn-2920000
	 [[Node: save/restore_slice_29 = RestoreSlice[dt=DT_FLOAT, preferred_shard=-1, _device="/job:localhost/replica:0/task:0/cpu:0"](_recv_save/Const_0, save/restore_slice_29/tensor_name, save/restore_slice_29/shape_and_slice)]]
Traceback (most recent call last):
  File "deep_q_network.py", line 215, in <module>
    main()
  File "deep_q_network.py", line 212, in main
    playGame()
  File "deep_q_network.py", line 209, in playGame
    trainNetwork(s, readout, h_fc1, sess)
  File "deep_q_network.py", line 109, in trainNetwork
    saver.restore(sess, checkpoint.model_checkpoint_path)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/training/saver.py", line 864, in restore
    sess.run([self._restore_op_name], {self._filename_tensor_name: save_path})
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/client/session.py", line 345, in run
    results = self._do_run(target_list, unique_fetch_targets, feed_dict_string)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/client/session.py", line 419, in _do_run
    e.code)
tensorflow.python.framework.errors.NotFoundError: Unsuccessful TensorSliceReader constructor: Failed to find any matching files for bird-dqn-2920000
	 [[Node: save/restore_slice = RestoreSlice[dt=DT_FLOAT, preferred_shard=-1, _device="/job:localhost/replica:0/task:0/cpu:0"](_recv_save/Const_0, save/restore_slice/tensor_name, save/restore_slice/shape_and_slice)]]
Caused by op u'save/restore_slice', defined at:
  File "deep_q_network.py", line 215, in <module>
    main()
  File "deep_q_network.py", line 212, in main
    playGame()
  File "deep_q_network.py", line 209, in playGame
    trainNetwork(s, readout, h_fc1, sess)
  File "deep_q_network.py", line 105, in trainNetwork
    saver = tf.train.Saver()
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/training/saver.py", line 688, in __init__
    restore_sequentially=restore_sequentially)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/training/saver.py", line 408, in build
    filename_tensor, vars_to_save, restore_sequentially, reshape)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/training/saver.py", line 166, in _AddRestoreOps
    values = self.restore_op(filename_tensor, vs, preferred_shard)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/training/saver.py", line 83, in restore_op
    preferred_shard=preferred_shard)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/ops/io_ops.py", line 169, in _restore_slice
    preferred_shard, name=name)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/ops/gen_io_ops.py", line 271, in _restore_slice
    preferred_shard=preferred_shard, name=name)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/ops/op_def_library.py", line 633, in apply_op
    op_def=op_def)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/framework/ops.py", line 1710, in create_op
    original_op=self._default_original_op, op_def=op_def)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/framework/ops.py", line 988, in __init__
    self._traceback = _extract_stack()
```

And this is with preprended dir:
```
[petr@hellmut DeepLearningFlappyBird (master)]$ nano saved_networks/checkpoint 
[petr@hellmut DeepLearningFlappyBird (master ✗)]$ python deep_q_network.py      
I tensorflow/core/common_runtime/local_device.cc:25] Local device intra op parallelism threads: 4
I tensorflow/core/common_runtime/local_session.cc:45] Local session inter op parallelism threads: 4
Successfully loaded: saved_networks/bird-dqn-2920000
TIMESTEP 1 / STATE observe / EPSILON 0.0001 / ACTION 0 / REWARD 0.1 / Q_MAX 1.162439e+01
TIMESTEP 2 / STATE observe / EPSILON 0.0001 / ACTION 0 / REWARD 0.1 / Q_MAX 1.167451e+01
TIMESTEP 3 / STATE observe / EPSILON 0.0001 / ACTION 0 / REWARD 0.1 / Q_MAX 1.166384e+01
TIMESTEP 4 / STATE observe / EPSILON 0.0001 / ACTION 0 / REWARD 0.1 / Q_MAX 1.158778e+01
TIMESTEP 5 / STATE observe / EPSILON 0.0001 / ACTION 0 / REWARD 0.1 / Q_MAX 1.163115e+01
TIMESTEP 6 / STATE observe / EPSILON 0.0001 / ACTION 0 / REWARD 0.1 / Q_MAX 1.166643e+01
...
```

**Comment by yenchenlin1994** [comment]
Thx @petrbel ,
Although I can't reproduce it, I would like to fix it.

May you enter the Python shell and type
```python
import tensorflow
tensorflow.__version__
```
?

**Comment by petrbel** [comment]
Sure!

```python
>>> import tensorflow
>>> tensorflow.__version__
'0.7.1'
```

**Comment by yenchenlin1994** [comment]
Thanks @petrbel ,
sorry I can't find out what's the issue, therefore I add [a section](https://github.com/yenchenlin1994/DeepLearningFlappyBird#checkpoint-not-found) in README about this.
I'll try to figure out if there are more reports like this.

**Comment by petrbel** [comment]
Thanks @yenchenlin1994 , I think it's ok this way. Everybody can search the issue and try it :) I'll ask some other guys to try it.
